List<Map<String, String>> lastCities = [
  {"name": "Afragola"},
  {"name": "Agrigento"},
  {"name": "Ala"},
  {"name": "Alessandria"},
  {"name": "Alghero"},
  {"name": "Altre"},
  {"name": "Ancona"},
  {"name": "Aosta"},
  {"name": "Arco Felice"},
  {"name": "Arezzo"},
  {"name": "Ariano Irpino"},
  {"name": "Ascoli Piceno"},
  {"name": "Asiago"},
  {"name": "Assisi"},
  {"name": "Asti"},
  {"name": "Avellino"},
  {"name": "Aversa"},
  {"name": "Avezzano"},
  {"name": "Bari"},
  {"name": "Barletta"},
  {"name": "Baronissi"},
  {"name": "Benevento"},
  {"name": "Bergamo"},
  {"name": "Biella"},
  {"name": "Bologna"},
  {"name": "Bolzano"},
  {"name": "Bra"},
  {"name": "Bracciano"},
  {"name": "Brescia"},
  {"name": "Bressanone"},
  {"name": "Brindisi"},
  {"name": "Brunico"},
  {"name": "Buenos Aires"},
  {"name": "Cagliari"},
  {"name": "Calenzano"},
  {"name": "Caltanissetta"},
  {"name": "Camerino"},
  {"name": "Campobasso"},
  {"name": "Canazei"},
  {"name": "Capua"},
  {"name": "Carrara"},
  {"name": "Casarza Ligure"},
  {"name": "Cassino"},
  {"name": "Castelfranco Veneto"},
  {"name": "Castellamare di Stabia"},
  {"name": "Castellanza"},
  {"name": "Casterta"},
  {"name": "Catania"},
  {"name": "Catanzaro"},
  {"name": "Cava de' Tirreni"},
  {"name": "Cecina"},
  {"name": "Cento"},
  {"name": "Cerignola"},
  {"name": "Cernusco sul Naviglio"},
  {"name": "Cesano Moderno"},
  {"name": "Cesena"},
  {"name": "Chiari"},
  {"name": "Chiavari"},
  {"name": "Chieti"},
  {"name": "Chioggia"},
  {"name": "Cisterna di Latina"},
  {"name": "Cittaducale"},
  {"name": "Civitanova Marche"},
  {"name": "Civitavecchia"},
  {"name": "Colle Val d'Elsa"},
  {"name": "Colorno"},
  {"name": "Comiso"},
  {"name": "Como"},
  {"name": "Conegliano"},
  {"name": "Cosenza"},
  {"name": "Crema"},
  {"name": "Cremona"},
  {"name": "Cuneo"},
  {"name": "Dalmine"},
  {"name": "Desenzano del Garda"},
  {"name": "Domodossola"},
  {"name": "Edolo"},
  {"name": "Empoli"},
  {"name": "Enna"},
  {"name": "Esine"},
  {"name": "Faenza"},
  {"name": "Fano"},
  {"name": "Feltre"},
  {"name": "Fermo"},
  {"name": "Ferrara"},
  {"name": "Figline Valdarno"},
  {"name": "Firenze"},
  {"name": "Fisciano"},
  {"name": "Foggia"},
  {"name": "Foligno"},
  {"name": "Follonica"},
  {"name": "Forlì"},
  {"name": "Frattaminore"},
  {"name": "Frosinone"},
  {"name": "Gargnano"},
  {"name": "Gemona del Friuli"},
  {"name": "Genova"},
  {"name": "Gorizia"},
  {"name": "Grosseto"},
  {"name": "Grugliasco"},
  {"name": "Gubbio"},
  {"name": "Iglesias"},
  {"name": "Imperia"},
  {"name": "Isernia"},
  {"name": "Ivrea"},
  {"name": "Jesi"},
  {"name": "L'Aquila"},
  {"name": "La Spezia"},
  {"name": "Lagonegro"},
  {"name": "Lamezia Terme"},
  {"name": "Lanciano"},
  {"name": "Lancusi"},
  {"name": "Latina"},
  {"name": "Lecce"},
  {"name": "Lecco"},
  {"name": "Legnaro"},
  {"name": "Lentini"},
  {"name": "Livorno"},
  {"name": "Locri"},
  {"name": "Lodi"},
  {"name": "Lucca"},
  {"name": "Lucera"},
  {"name": "Macerata"},
  {"name": "Malindi"},
  {"name": "Manfredonia"},
  {"name": "Mantova"},
  {"name": "Marcianise"},
  {"name": "Massa"},
  {"name": "Matelica"},
  {"name": "Matera"},
  {"name": "Mesagne"},
  {"name": "Messina"},
  {"name": "Mestre"},
  {"name": "Milano"},
  {"name": "Mirano"},
  {"name": "Modena"},
  {"name": "Modica"},
  {"name": "Mondovì"},
  {"name": "Monserrato"},
  {"name": "Monza"},
  {"name": "Napoli"},
  {"name": "Narni"},
  {"name": "Niscemi"},
  {"name": "Nola"},
  {"name": "Noto"},
  {"name": "Novara"},
  {"name": "Novedrate"},
  {"name": "Nuoro"},
  {"name": "Olbia"},
  {"name": "Origia"},
  {"name": "Oristano"},
  {"name": "Orvieto"},
  {"name": "Osimo"},
  {"name": "Padova"},
  {"name": "Palermo"},
  {"name": "Parma"},
  {"name": "Pavia"},
  {"name": "Perugia"},
  {"name": "Pesacara"},
  {"name": "Pesaro"},
  {"name": "Pescara"},
  {"name": "Pesche"},
  {"name": "Piacenza"},
  {"name": "Piazza Armerina"},
  {"name": "Pietra Ligure"},
  {"name": "Pieve di Cento"},
  {"name": "Pieve Emanuele"},
  {"name": "Pisa"},
  {"name": "Pistoia"},
  {"name": "Pomezia"},
  {"name": "Pomigliano d'Arco"},
  {"name": "Pontedera"},
  {"name": "Pordenone"},
  {"name": "Portici"},
  {"name": "Portogruaro"},
  {"name": "Potenza"},
  {"name": "Pozzilli"},
  {"name": "Prato"},
  {"name": "Priolo Gargallo"},
  {"name": "Ragusa"},
  {"name": "Ravenna"},
  {"name": "Recanati"},
  {"name": "Reggio Calabria"},
  {"name": "Reggio Emilia"},
  {"name": "Rieti"},
  {"name": "Rimini"},
  {"name": "Roma"},
  {"name": "Rosignano Marittimo"},
  {"name": "Rovereto"},
  {"name": "Rovigo"},
  {"name": "Rozzano"},
  {"name": "Salerno"},
  {"name": "San Benedetto del Tronto"},
  {"name": "San Donato Milanese"},
  {"name": "San Giovanni Rotondo"},
  {"name": "San Giovanni Valdarno"},
  {"name": "San Severo"},
  {"name": "Santa Maria Capua Vetere"},
  {"name": "Sarzana"},
  {"name": "Sassari"},
  {"name": "Savigliano"},
  {"name": "Savona"},
  {"name": "Segrate"},
  {"name": "Selargius"},
  {"name": "Sesto Fiorentino"},
  {"name": "Sesto San Giovanni"},
  {"name": "Siena"},
  {"name": "Siracusa"},
  {"name": "Spinetoli"},
  {"name": "Sulmona"},
  {"name": "Taranto"},
  {"name": "Tempio Pausania"},
  {"name": "Teramo"},
  {"name": "Termoli"},
  {"name": "Terni"},
  {"name": "Terracina"},
  {"name": "Torino"},
  {"name": "Torrazza Coste"},
  {"name": "Torre de' Passeri"},
  {"name": "Torre del Greco"},
  {"name": "Torrevecchia Teatina"},
  {"name": "Trani"},
  {"name": "Trapani"},
  {"name": "Trento"},
  {"name": "Treviglio"},
  {"name": "Treviso"},
  {"name": "Trieste"},
  {"name": "Udine"},
  {"name": "Urbino"},
  {"name": "Valenzano"},
  {"name": "Varese"},
  {"name": "Vasto"},
  {"name": "Venezia"},
  {"name": "Verbania"},
  {"name": "Vercelli"},
  {"name": "Verona"},
  {"name": "Viareggio"},
  {"name": "Vibo Valentia"},
  {"name": "Vicenza"},
  {"name": "Viterbo"},
  {"name": "Vittorio Veneto"}
];
